<a href="https://colab.research.google.com/github/mohanveeramanikantak/K-Hub-Machine-Learning/blob/main/Task%201%20(%20data_preprocessing_tools%20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [16]:
import pandas as pd

df = pd.read_csv("/content/Data (1).csv")

In [23]:
print("DataFrame Info:")
df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [24]:
print("\nFirst 5 rows of the DataFrame:")
print(df.head())


First 5 rows of the DataFrame:
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


## Importing the dataset

In [ ]:
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [17]:
X = df.iloc[:, :-1].values
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [27]:
y = df.iloc[:, -1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [28]:
import numpy as np
from sklearn.impute import SimpleImputer

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

print("After handling missing data:\n", X)


After handling missing data:
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [31]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding the Dependent Variable

In [35]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Splitting the dataset into the Training set and Test set

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train)

[['Spain' 38.77777777777778 52000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 44.0 72000.0]
 ['Spain' 38.0 61000.0]
 ['Spain' 27.0 48000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 35.0 58000.0]]


In [40]:
print(X_test)

[['Germany' 30.0 54000.0]
 ['France' 37.0 67000.0]]


In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
print(y_train)

[0 1 0 0 1 1 0 1]


In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_test = le.fit_transform(y_test)
print(y_test)

[0 1]


## Feature Scaling

In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
import numpy as np

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [53]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

print(X_train)

[[1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358058
  -0.19159184384578554 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414834 1.7320508075688774 -0.7745966692414835
  -0.014117293757057846 -0.07013167641635404]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414835
  0.5667085065333239 0.6335624327104546]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358058
  -0.3045301939022487 -0.307866172742979]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358058
  -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414835
  1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414834 1.7320508075688774 -0.7745966692414835
  1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414835
  -0.7401495441200352 -0.5646194287757336]]
